courses/urls.py
from django.urls import path, include
from . import views

app_name = 'courses'
urlpatterns = [
    path('', views.course_list, name='list'),
    path('<int:course_pk>/<int:lesson_pk>/', views.lesson_detail, name='lesson'),
    path('<int:pk>/', views.course_detail, name='detail'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.hello_world, name="home"),
    path('courses/', include('courses.urls')),
]

urlpatterns += staticfiles_urlpatterns()

courses/models.py
from django.db import models


# Create your models here.
class Course(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=255)
    description = models.TextField()

    def __str__(self):
        return self.title


class Lesson(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    content = models.TextField(blank=True, default="")
    order = models.IntegerField(default=0)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)

    class Meta:
        ordering = ['order',]

    def __str__(self):
        return self.title

courses/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse

from .models import Course, Lesson


# Create your views here.
def course_list(request):
    courses = Course.objects.all()
    email = 'e.ventura@caribbeandigitalgroup.com'
    # response = ', '.join([str(course) for course in courses])
    # return HttpResponse(response)
    return render(request, 'courses/course_list.html', {'courses': courses, 'email':email})


def course_detail(request,pk):
    # course = Course.objects.get(pk=pk)
    course = get_object_or_404(Course,pk=pk)
    return render(request, 'courses/course_detail.html', {'course': course})


def lesson_detail(request, course_pk, lesson_pk):
    lesson = get_object_or_404(Lesson, course_id=course_pk, pk=lesson_pk)
    return render(request, 'courses/lesson_detail.html', {'lesson': lesson})

mysite/views.py
# from django.http import HttpResponse
from django.shortcuts import render


def hello_world(request):
    # return HttpResponse("Hello World")
    return render(request, 'home.html')

courses/templates/courses/course_detail.html
{% extends "layout.html" %}
{% load humanize course_extras %}
{% block title %}{{course.title}}{% endblock %}
{% block content %}
<article>
    <h2>
        <a href="{% url 'courses:detail' pk=course.pk %}">{{course.title}}</a>
    </h2>
    {{course.description|markdown_to_html|safe}}

    <p>
        Hay <strong> {{ course.lesson_set.count|apnumber }} </strong> leccion{{ course.lesson_set.count|pluralize:"es" }} en este curso: {{ course.lesson_set.all|join:", " }}
    </p>

    <hr/>
    <section>
        {% for lesson in course.lesson_set.all %}
        <h3>
            <a href="{% url 'courses:lesson' course_pk=lesson.course.pk lesson_pk=lesson.pk %}">{{lesson.title}}</a>
        </h3>

            {{lesson.description}}
            {{lesson.content|markdown_to_html|safe}}
        {% endfor %}
    </section>

</article>
{% endblock %}

courses/templates/courses/course_list.html
{% extends 'layout.html' %}
{% load static from static %}
{% block static %}
<link rel="stylesheet" href="{% static 'courses/css/style.css' %}">
{% endblock %}
{% block title %} Cursos disponibles {% endblock %}
{% block content %}

{% for course in courses %}
    <div class="card">
        <header>
            <a href="{% url 'courses:detail' pk=course.pk %}">
                {{ course.title }}
            </a>
        </header>
        <div class="card-copy">
            {% if course.description|wordcount <= 5 %}
                {{course.description}}
            {% else %}
                {{course.description|truncatewords:5}}
                <a href="{% url 'courses:detail' pk=ourse.pk %}">leer mas</a>
            {% endif %}
            <div>
                Creado el: {{ course.created_at|date:"d-m-y" }}
            </div>
        </div>
    </div>
{% endfor %}
    <div>
        Contacto:
        <a href="mailto:{{ email }}">Correo</a> <br/>
        {{ email|urlize }}
    </div>

{% endblock %}

courses/templates/courses/lesson_detail.html
{% extends "layout.html" %}
{% load course_extras %}

{% block title %}
{{lesson.title}} - {{lesson.course.title}}
{% endblock %}

{% block content %}
<article>
    <h2>
        <a href="{% url 'courses:detail' pk=lesson.course.pk %}">{{lesson.course.title}}</a>
    </h2>
    <h3>{{lesson.title}}</h3>
    {{lesson.description|linebreaks}}
    {{lesson.content|linebreaks}}

    {% with content=lesson.content %}
        {{content|linebreaks}}
        Contenido: {{ content|wordcount }} palabras.
        Tiempo estimado: {{ content|wordcount|time_estimate }} minuto{{content|wordcount|time_estimate|pluralize}}.
    {% endwith%}
</article>
{% endblock %}

mysite/templates/home.html
{% extends "layout.html" %}
{% block title %}mysite{% endblock %}
{% block content %}
    <h3>Hola mundo</h3>
{% endblock %}

mysite/templates/layout.html
{% load static from static %}
{% load course_extras %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/layout.css' %}">
    {% block static %}{% endblock %}
</head>
<body>
    <div class="site-container">
        <nav>
            <a href="{% url 'home' %}">My site</a>
            <a href="{% url 'courses:list' %}">Cursos</a>
        </nav>
        <p>No te pierdas nuestro ultimo curso: {% last_course %}</p>
        {% block content %}{% endblock %}
    </div>
</body>
</html>